server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: camunda-workflow
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

kafka:
  topics:
    notifications: notification-events

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    history-level: full