spring:
  application:
    name: transaction-service
  data:
    redis:
      host: localhost
      port: 6379

  jackson:
    default-property-inclusion: non_null

kafka:
  topics:
    approved: transactions-approved
    rejected: transactions-rejected

server:
  port: 8081
  error:
    include-message: always